# An example of ClusterConfig showing different ways of setting nodegroup SSH keys:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-7
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/id_rsa_tests.pub
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import default public key (~/.ssh/id_rsa.pub)
      allow: true
  - name: ng-3
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
  - name: ng-4
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import inline public key
      publicKey: "ssh-rsa abcd"
  - name: ng-5
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # use existing EC2 key but don't allow SSH access to nodegroup (security group is not created to allow SSH access).
      publicKeyName: ec2_dev_key
      allow: false
  - name: ng-6
    instanceType: m5.large
    desiredCapacity: 1
    ssh:
      enableSsm: true
  - name: ng-7
    instanceType: m5.large
    desiredCapacity: 1
    # no SSH
